Config:
  # Debug :)
  # -1 = off
  # 0 = errors
  # 1 = setting stuff + command stuff (default)
  # 2 = event stuff
  # 3 = schedule stuff
  # 4 = spam :)
  Debug: 1
  # text = Use yaml property (default)
  # json = Use json flat file
  # !mysql = Use Mysql
  # !sqlite = Use sqlite
  Database: text
Mysql:
  host: localhost
  port: 3306
  name: minecraft
  user: root
  password: password
